### ISSUE TITLE
Allow user to pass a URL argument

### ISSUE THREAD

**Issue by dougiebuckets** [dougiebuckets/github-email-scraper#4]
Might be cool to allow the user to pass any location-based Github profile query as an argument. 

e.g.

$ ruby github-email-scraper https://github.com/search?q=location%3ABuffalo%2CNY&type=Users

**Comment by ecandino** [comment]
Yeah definitely

**Comment by dougiebuckets** [comment]
Addressed this in https://github.com/dougiebuckets/github-email-scraper/commit/b3a0c8dd76a66fd1126a2ada4c0182a2175469d0
